### ISSUE TITLE
Sentiment Analysis

### ISSUE THREAD

**Issue by shruti-2412** [Mozilla-Campus-Club-Cummins/AI-ML-HacktoberFest23#5]
Develop a model that can determine the sentiment of a given text (e.g., positive, negative, or neutral) to automate the analysis of customer reviews, social media comments, or other text-based data. You can use any dataset.

**Comment by bargeshreeya** [comment]
I would like to work on this issue .
Shreeya Barge TY IT
UIT2021810

**Comment by shruti-2412** [comment]
You can start working on the issue
